use_frameworks!
platform :ios, '11.0'

target 'CloudsImporting_Example' do
  pod 'CloudsImporting', :path => '../'
  pod 'Extensions', :git => 'https://github.com/AlexKarpov/Extensions.git'

  target 'CloudsImporting_Tests' do
    inherit! :search_paths

    
  end
end
